const formula = [

    {
        day: 1,
        multiplier: 0.8,
        reps: '12',
        sets: {
            squats: 3,
            benchpress: 2,
            row: 2,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 2,
        multiplier: 0.85,
        reps: '12',
        sets: {
            squats: 3,
            benchpress: 2,
            row: 2,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 3,
        multiplier: 0.9,
        reps: '12',
        sets: {
            squats: 3,
            benchpress: 2,
            row: 2,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 4,
        multiplier: 0.95,
        reps: '8',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 5,
        multiplier: 0.975,
        reps: '8',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 6,
        multiplier: 1,
        reps: '8',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 7,
        multiplier: 1.025,
        reps: '8',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 8,
        multiplier: 1.05,
        reps: '8',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 9,
        multiplier: 1.075,
        reps: '8',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 10,
        multiplier: 1.1,
        reps: '8',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 11,
        multiplier: 1.125,
        reps: '8',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 12,
        multiplier: 1.15,
        reps: '8',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 13,
        multiplier: 1.3,
        reps: '4+1',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 14,
        multiplier: 1.318,
        reps: '4+1',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 15,
        multiplier: 1.336,
        reps: '4+1',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 16,
        multiplier: 1.354,
        reps: '4+1',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 17,
        multiplier: 1.372,
        reps: '4+1',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    {
        day: 18,
        multiplier: 1.39,
        reps: '4+1',
        sets: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
];

export default formula;
