const formula = {

    1: {
        multiplier: 0.8,
        reps: '12',
        set: {
            squats: 3,
            benchpress: 2,
            row: 2,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    2: {
        multiplier: 0.85,
        reps: '12',
        set: {
            squats: 3,
            benchpress: 2,
            row: 2,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    3: {
        multiplier: 0.9,
        reps: '12',
        set: {
            squats: 3,
            benchpress: 2,
            row: 2,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    4: {
        multiplier: 0.95,
        reps: '8',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    5: {
        multiplier: 0.975,
        reps: '8',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    6: {
        multiplier: 1,
        reps: '8',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    7: {
        multiplier: 1.025,
        reps: '8',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    8: {
        multiplier: 1.05,
        reps: '8',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    9: {
        multiplier: 1.075,
        reps: '8',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    10: {
        multiplier: 1.1,
        reps: '8',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    11: {
        multiplier: 1.125,
        reps: '8',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    12: {
        multiplier: 1.15,
        reps: '8',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 2,
            biceps: 2,
            triceps: 2,
        },
    },
    13: {
        multiplier: 1.3,
        reps: '4+1',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    14: {
        multiplier: 1.318,
        reps: '4+1',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    15: {
        multiplier: 1.336,
        reps: '4+1',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    16: {
        multiplier: 1.354,
        reps: '4+1',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    17: {
        multiplier: 1.372,
        reps: '4+1',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    },
    18: {
        multiplier: 1.39,
        reps: '4+1',
        set: {
            squats: 3,
            benchpress: 3,
            row: 3,
            abs: 3,
            arnold: 3,
            biceps: 2,
            triceps: 2,
        },
    }
}

export default formula;
